### PR TITLE
Snapshot button

### PR DESCRIPTION
**Pull request by grancalavera**
## Description

This pull request introduces a simple `createSnapshotButton` component that allows to take a snapshot of the current data in the grid and produce an arbitrary side effect with it.

## Motivation and Context

We have a particular use case in which we need to create a printable version for a grid, preserving the current state: sort, filters, etc...

## How Was This Tested?

Using an example rig, see `examples/snapshot-button.html`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change follows the style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have read the [contribution guidelines](../CONTRIBUTING.md)
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by gabrielmontagne** [comment]
@grancalavera , thanks!

I spent a long while with @janesconference reviewing the API and going over the chat we had yesterday offline. We were initially trying to figure out if we could let the user control the gesture that triggers the "snapshot" instead of passing the button, and then wondering if something was fundamentally missing from the grid component itself that would be forcing us into having to write a component like this.

We cannot put an accessor on the grid itself because the grid is just a function that is run on a selection of potentially several DOM elements with different data bound to it.  

After a few reductions of the component we realized that the same could be achieved perhaps more transparently by doing something as simple as,

```javascript
const button = d3.select('#snapshot-button')
        .on('click', () => print(d3.select('.grid-target').datum()))

function print({rows, columns}) {
  d3.select('#snapshot-target')
    .datum(rows)
    .call(snapshotTable.columns(columns))
  // etc. 
}
```

How would something like that look for your case? 

I'm totally aware that the whole `d.rows.free`, `d.columns`, `d.rows.bottom`, etc. is absolutely opaque and lives in the dark and impenetrable Undocumentation Forest :fog:. 
Perhaps we can work -- maybe even on this branch? -- to clear that out, trim the snapshot example, etc. 

Also super happy about the rollup fixes :smiley:

**Comment by grancalavera** [comment]
> We were initially trying to figure out if we could let the user control the gesture that triggers the "snapshot" instead of passing the button

This is the actual use case, and we are moving in that direction already. I'll try the approach you are proposing which I think should work as well. Happy to close this PR and create a new one with the fixes for rollup only.

**Comment by janesconference** [comment]
Yes, basically we thought everyone would be happier to have a way to extract the `d` on-demand from the table rather than having to write an ad-hoc component to do the same thing for every use case.

I guess the real issue, in this case, is the lack of documentation :( 
Also, solving [this issue](https://github.com/zambezi/grid-components/issues/6 ), IMHO, would be of great help for our future users.

**Comment by grancalavera** [comment]
Should we assume the simple proposed approach is enough (adding any relevant missing documentation) or do we want to have an specialised API for this at the grid level?

**Comment by grancalavera** [comment]
I'm closing this because we don't want to go in this direction.

**Pull request closed without merging**
